Untested code that may fix the following:
Exception in thread Thread-2 (forward_text_lines):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/app/venv/lib/python3.12/site-packages/socrate/system.py", line 155, in forward_text_lines
    current_line = src.readline()
                   ^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa8 in position 166: invalid start byte

This was reported in #3398

(cherry picked from commit 61812ac32a96b06497e2d646a60b0a2f349f1937)